#+TITLE: Doom Emacs Configuration
#+AUTHOR: Lucas Cunegundes
#+EMAIL: lucascsantana6@gmail.com
#+DESCRIPTION: Configuração pessoal do Doom Emacs focada em Python/Django
#+STARTUP: fold
#+PROPERTY: header-args:emacs-lisp :tangle config.el :cache yes :results silent :padline no

* Table of Contents :TOC_3:noexport:
- [[#informações-pessoais][Informações Pessoais]]
- [[#aparência][Aparência]]
  - [[#fonte][Fonte]]
  - [[#tema-e-ui][Tema e UI]]
- [[#org-mode][Org Mode]]
- [[#python-development][Python Development]]
  - [[#lsp-mode--pyright][LSP Mode + Pyright]]
  - [[#formatação-apheleia--ruff][Formatação (Apheleia + Ruff)]]
  - [[#debug-dape][Debug (Dape)]]
- [[#keybindings][Keybindings]]
- [[#database-ejc-sql][Database (EJC-SQL)]]
- [[#terminal-vterm][Terminal (VTerm)]]

* Informações Pessoais
Configuração básica de identidade.

#+begin_src emacs-lisp
(setq user-full-name "Lucas Cunegundes"
      user-mail-address "lucascsantana6@gmail.com")
#+end_src

* Aparência

** Fonte
Iosevka Nerd Font Mono, tamanho 12.

#+begin_src emacs-lisp
(setq doom-font (font-spec :family "Iosevka Nerd Font Mono" :size 12))

(custom-set-faces!
  '(italic :slant italic)
  '(bold :weight bold)
  '(bold-italic :weight bold :slant italic))
#+end_src

** Tema e UI
Tokyo Night com números de linha relativos e beacon mode.

#+begin_src emacs-lisp
(setq doom-theme 'doom-tokyo-night
      display-line-numbers-type 'relative)

(beacon-mode 1)
#+end_src

* Org Mode
Configuração para organização pessoal, agenda e produtividade.

#+begin_src emacs-lisp
(use-package! org
  :config
  (setq org-directory "~/Documentos/"
        org-agenda-files '("~/Documentos/agenda.org")
        org-log-done 'time)
  (add-hook 'org-mode-hook #'org-bullets-mode))
#+end_src

* Python Development
Configuração completa para desenvolvimento Python com foco em Django + Docker.

** LSP Mode + Pyright
Language Server Protocol usando LSP Mode com Pyright/BasedPyright.

#+begin_src emacs-lisp
(after! python
  (setq python-shell-virtualenv-root ".venv")
  
  ;; LSP automático
  (add-hook 'python-mode-hook #'lsp-deferred)
  (add-hook 'python-ts-mode-hook #'lsp-deferred))

(after! lsp-pyright
  (setq lsp-pyright-langserver-command "basedpyright-langserver"
        lsp-pyright-auto-import-completions t
        lsp-pyright-auto-search-paths t
        lsp-pyright-use-library-code-for-types nil
        lsp-pyright-diagnostic-mode "openFilesOnly"
        lsp-pyright-type-checking-mode "off"))

(after! lsp-mode
  ;; Performance
  (setq lsp-idle-delay 0.5
        lsp-log-io nil
        lsp-completion-provider :capf
        lsp-enable-file-watchers nil
        lsp-enable-folding nil
        lsp-enable-text-document-color nil
        lsp-enable-on-type-formatting nil
        
        ;; UI Elements - TODOS DESABILITADOS
        lsp-headerline-breadcrumb-enable nil
        lsp-modeline-code-actions-enable nil
        lsp-modeline-diagnostics-enable nil
        lsp-modeline-workspace-status-enable nil
        lsp-signature-auto-activate nil
        lsp-signature-render-documentation nil
        lsp-lens-enable nil
        lsp-semantic-tokens-enable nil
        lsp-inlay-hint-enable nil))
#+end_src

Remove todas as marcações visuais do código.

#+begin_src emacs-lisp
(after! lsp-mode
  ;; DESABILITA diagnósticos completamente
  (setq lsp-diagnostics-provider :none)
  
  ;; Remove highlight de símbolos
  (custom-set-faces!
    '(lsp-face-highlight-textual :underline nil :background nil)
    '(lsp-face-highlight-read :underline nil :background nil)
    '(lsp-face-highlight-write :underline nil :background nil)))

(after! flymake
  ;; Configuração minimalista
  (setq flymake-show-diagnostics-at-end-of-line nil
        flymake-indicator-type nil)
  
  ;; Remove todos os underlines
  (custom-set-faces!
    '(flymake-error :underline nil)
    '(flymake-warning :underline nil)
    '(flymake-note :underline nil)))

(after! flycheck
  ;; Desabilita flycheck também
  (setq flycheck-indication-mode nil
        flycheck-highlighting-mode nil))
#+end_src

** Formatação (Apheleia + Ruff)
Auto-formatação on-save com Ruff.

#+begin_src emacs-lisp
(use-package! apheleia
  :hook ((python-mode python-ts-mode) . apheleia-mode)
  :config
  (setf (alist-get 'python-mode apheleia-mode-alist) '(ruff-isort ruff))
  (setf (alist-get 'python-ts-mode apheleia-mode-alist) '(ruff-isort ruff))
  
  (setf (alist-get 'ruff apheleia-formatters)
        '("ruff" "format" "--stdin-filename" filepath))
  (setf (alist-get 'ruff-isort apheleia-formatters)
        '("ruff" "check" "--select" "I" "--fix" "--stdin-filename" filepath)))
#+end_src

** Debug (Dape)
Debugger para Python em containers Docker.

#+begin_src emacs-lisp
(use-package! dape
  :config
  (setq dape-buffer-window-arrangement 'right
        dape-info-hide-mode-line t)

  (add-to-list
   'dape-configs
   `(python-docker
     modes (python-mode python-ts-mode)
     command "python"
     command-args ("-m" "debugpy.adapter")
     port 5678
     host "127.0.0.1"
     cwd ,(lambda () (or (projectile-project-root) default-directory))
     path-mappings
     (,(lambda ()
         (list
          (cons
           (or (projectile-project-root) default-directory)
           "/app"))))))

  (add-to-list
   'dape-configs
   `(python-docker-alianca
     modes (python-mode python-ts-mode)
     command "python"
     command-args ("-m" "debugpy.adapter")
     port 5678
     host "127.0.0.1"
     cwd "/home/lucas/Projects/work/alianca/apps/backend/"
     path-mappings
     (("/home/lucas/Projects/work/alianca/apps/backend/" . "/app")))))
#+end_src

* Keybindings
Atalhos customizados para LSP Mode.

#+begin_src emacs-lisp
(map! :leader
      (:prefix ("c" . "code")
       :desc "Code actions"        "a" #'lsp-execute-code-action
       :desc "Rename symbol"       "r" #'lsp-rename
       :desc "Format buffer"       "f" #'apheleia-format-buffer
       :desc "Organize imports"    "o" #'lsp-organize-imports
       :desc "Hover doc"           "k" #'lsp-describe-thing-at-point)
      
      (:prefix ("g" . "goto")
       :desc "Definition"          "d" #'lsp-find-definition
       :desc "References"          "r" #'lsp-find-references
       :desc "Implementations"     "i" #'lsp-find-implementation
       :desc "Type definition"     "t" #'lsp-find-type-definition))
#+end_src

* Database (EJC-SQL)
Cliente SQL interativo para PostgreSQL.

#+begin_src emacs-lisp
(use-package! ejc-sql
  :commands (ejc-sql-mode ejc-sql-connect)
  :config
  (setq ejc-sql-separator ";"
        ejc-use-flx t
        ejc-result-table-impl 'ejc-result-table-tabulated))

(after! ejc-sql
  (ejc-create-connection
   "postgres-nexus"
   :classpath (ejc-find-postgres-jdbc)
   :dbtype "postgresql"
   :dbname "nexus_rfid"
   :host "localhost"
   :port 5432
   :user "postgres")

  (ejc-create-connection
   "postgres-alianca"
   :classpath (ejc-find-postgres-jdbc)
   :dbtype "postgresql"
   :dbname "alianca_rfid"
   :host "localhost"
   :port 5432
   :user "postgres"))
#+end_src

* Terminal (VTerm)
Terminal emulado com ZSH.

#+begin_src emacs-lisp
(use-package! vterm
  :commands vterm
  :config
  (setq vterm-shell "/bin/zsh"))
#+end_src
