#!/usr/bin/env bash

options=("Gemini" "Qwen" "Opencode")

IA=$(printf "%s\n" "${options[@]}" | fzf --prompt="Escolha uma IA: " --height 10 --border)

if [ -z "$IA" ]; then
    echo "Nenhuma IA selecionada. Saindo..."
    exit 1
fi

clear
echo "Iniciando $IA..."
sleep 0.5

case $IA in
Gemini) gemini ;;
Qwen) qwen ;;
Opencode) opencode ;;
esac
