vim.defer_fn(function()
  pcall(require, 'plugins.cmp')
  pcall(require, 'plugins.treesitter')
  pcall(require, 'plugins.lualine')
  pcall(require, 'plugins.mini')
  pcall(require, 'plugins.whichkey')
  pcall(require, 'plugins.conform')
  pcall(require, 'plugins.dap')
  pcall(require, 'plugins.fzf')
  pcall(require, 'plugins.gitsigns')
  pcall(require, 'plugins.catppuccin')
end, 0)
