return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  event = { 'BufReadPre', 'BufNewFile' },
  dependencies = {
    'nvim-treesitter/nvim-treesitter-textobjects',
    'nvim-treesitter/nvim-treesitter-context',
    'windwp/nvim-ts-autotag',
  },
  config = function()
    require('nvim-treesitter.configs').setup {
      modules = {},
      ensure_installed = {
        'c',
        'cpp',
        'go',
        'rust',
        'cmake',
        'bash',
        'lua',
        'vim',
        'vimdoc',
        'html',
        'css',
        'javascript',
        'typescript',
        'tsx',
        'json',
        'yaml',
        'toml',
        'markdown',
        'markdown_inline',
        'python',
      },
      sync_install = false,
      auto_install = true,
      ignore_install = {},

      highlight = {
        enable = true,
        disable = {
          -- add languages. Ex.: "markdown", "toml", etc
        },
        additional_vim_regex_highlighting = false,
      },
      indent = {
        enable = true,
      },
      autotag = {
        enable = true,
      },
      textobjects = {
        select = {
          enable = true,
          lookahead = true,
          keymaps = {
            ['af'] = '@function.outer',
            ['if'] = '@function.inner',
            ['ac'] = '@class.outer',
            ['ic'] = '@class.inner',
            ['ai'] = '@conditional.outer',
            ['ii'] = '@conditional.inner',
            ['al'] = '@loop.outer',
            ['il'] = '@loop.inner',
            ['am'] = '@call.outer',
            ['im'] = '@call.inner',
            ['ab'] = '@block.outer',
            ['ib'] = '@block.inner',
            ['aa'] = '@parameter.outer',
            ['ia'] = '@parameter.inner',
            ['a/'] = '@comment.outer',
            ['i/'] = '@comment.inner',
            ['as'] = '@statement.outer',
            ['ga='] = '@assignment.outer',
            ['gi='] = '@assignment.inner',
            ['gl='] = '@assignment.lhs',
            ['gr='] = '@assignment.rhs',
            ['ar'] = '@return.outer',
            ['ir'] = '@return.inner',
            ['az'] = '@regex.outer',
            ['iz'] = '@regex.inner',
          },
        },
        move = {
          enable = true,
          set_jumps = true,
          goto_next_start = {
            [']f'] = '@function.outer',
            [']c'] = '@class.outer',
            [']i'] = '@conditional.outer',
            [']l'] = '@loop.outer',
            [']m'] = '@call.outer',
            [']b'] = '@block.outer',
            [']a'] = '@parameter.inner',
            [']/'] = '@comment.outer',
            [']s'] = '@statement.outer',
            [']='] = '@assignment.outer',
            [']r'] = '@return.outer',
          },
          goto_next_end = {
            [']F'] = '@function.outer',
            [']C'] = '@class.outer',
            [']I'] = '@conditional.outer',
            [']L'] = '@loop.outer',
            [']M'] = '@call.outer',
            [']B'] = '@block.outer',
            [']A'] = '@parameter.inner',
          },
          goto_previous_start = {
            ['[f'] = '@function.outer',
            ['[c'] = '@class.outer',
            ['[i'] = '@conditional.outer',
            ['[l'] = '@loop.outer',
            ['[m'] = '@call.outer',
            ['[b'] = '@block.outer',
            ['[a'] = '@parameter.inner',
            ['[/'] = '@comment.outer',
            ['[s'] = '@statement.outer',
            ['[='] = '@assignment.outer',
            ['[r'] = '@return.outer',
          },
          goto_previous_end = {
            ['[F'] = '@function.outer',
            ['[C'] = '@class.outer',
            ['[I'] = '@conditional.outer',
            ['[L'] = '@loop.outer',
            ['[M'] = '@call.outer',
            ['[B'] = '@block.outer',
            ['[A'] = '@parameter.inner',
          },
        },
        swap = {},
      },
    }
    require('treesitter-context').setup {
      enable = true,
      max_lines = 3,
      multiline_threshold = 2,
      trim_scope = 'outer',
    }
  end,
}
