cursor #e5e2e0
cursor_text_color #c9c6bd

foreground            #e5e2e0
background            #141312
selection_foreground  #31302c
selection_background  #c9c6c0
url_color             #c9c7bb

color0   #141312
color1   #e77568
color2   #71c964
color3   #fbe571
color4   #bebcae
color5   #5d5b51
color6   #c9c7bb
color7   #d3d0c6
color8   #828178
color9   #ffa99f
color10  #a7f19c
color11  #fff0a5
color12  #dddbd0
color13  #fffdf2
color14  #fffdf7
color15  #fffdf8
