cursor #e6e1e3
cursor_text_color #c9c5cd

foreground            #e6e1e3
background            #141315
selection_foreground  #322f38
selection_background  #cac4d0
url_color             #cac3dd

color0   #141315
color1   #fe728f
color2   #6edd85
color3   #ffda72
color4   #bcb4d1
color5   #565066
color6   #cac3dd
color7   #dddae8
color8   #87848f
color9   #ff9fb3
color10  #a5ffb8
color11  #ffe7a5
color12  #e1daf3
color13  #efeaff
color14  #f5f1ff
color15  #faf8ff
