cursor #e3e2e3
cursor_text_color #c3c7cc

foreground            #e3e2e3
background            #121314
selection_foreground  #293137
selection_background  #bfc7cf
url_color             #b3cadb

color0   #121314
color1   #fb719c
color2   #6ddb7b
color3   #fff772
color4   #a2bcd0
color5   #435665
color6   #b3cadb
color7   #d8dfe5
color8   #83898e
color9   #ff9fbc
color10  #a5ffb0
color11  #fff9a5
color12  #cbe1f0
color13  #def1ff
color14  #eaf6ff
color15  #f8fcff
