# BEGIN_KITTY_THEME
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

#: Shell & Scrollback

shell_integration enabled
scrollback_pager_history_size 100
scrollback_pager nvim -u NONE -c "setlocal nonumber norelativenumber" -c "silent write! /tmp/kitty_scrollback_buffer | te cat /tmp/kitty_scrollback_buffer - "

#: Clipboard & Copy

clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask
copy_on_select clipboard
clear_selection_on_clipboard_loss clipboard

#: Remote Control

allow_remote_control socket-only
listen_on unix:/tmp/kitty-{kitty_pid}

#: Layout

enabled_layouts tall
remember_window_size yes

#: Window

confirm_os_window_close 0
window_padding_width 5
window_margin_width 5
enable_audio_bell no

#: Cursor

mouse_hide_wait 3.0
cursor_shape block
cursor_blink true
cursor_trail 10
cursor_trail_start_threshold 0
cursor_trail_decay 0.01 0.05

#: Tab Bar — Vesper style

tab_bar_style powerline
tab_powerline_style slanted
tab_bar_align left
tab_bar_edge bottom
tab_bar_min_tabs 1
tab_title_max_length 30

#: Keybindings — Vim-like

kitty_mod alt
clear_all_shortcuts

#: Navigation — h/j/k/l
map kitty_mod+h neighboring_window left
map kitty_mod+j neighboring_window down
map kitty_mod+k neighboring_window up
map kitty_mod+l neighboring_window right

#: Splits — like vim :sp / :vsp
map kitty_mod+shift+v launch --type=window --cwd=current zsh
map kitty_mod+shift+s launch --type=window --cwd=current zsh

#: Windows & Tabs
map kitty_mod+w close_window
map kitty_mod+enter new_window
map kitty_mod+t new_tab
map kitty_mod+] next_tab
map kitty_mod+[ previous_tab

#: Resize (repeatable)
map kitty_mod+shift+h resize_window narrower
map kitty_mod+shift+l resize_window wider
map kitty_mod+shift+k resize_window taller
map kitty_mod+shift+j resize_window shorter

#: Tabs — kitty_mod+number para ir direto à tab
map kitty_mod+1 goto_tab 1
map kitty_mod+2 goto_tab 2
map kitty_mod+3 goto_tab 3
map kitty_mod+4 goto_tab 4
map kitty_mod+5 goto_tab 5
map kitty_mod+6 goto_tab 6
map kitty_mod+7 goto_tab 7
map kitty_mod+8 goto_tab 8
map kitty_mod+9 goto_tab 9
map kitty_mod+0 goto_tab -1

#: System — reload config, debug, fullscreen
map kitty_mod+shift+r load_config_file
map kitty_mod+shift+enter toggle_fullscreen
map kitty_mod+escape kitty_shell window

#: Font size
map ctrl+shift+equal change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0
map ctrl+shift+backspace change_font_size all 0
